## Notebook 1: Business Understanding & Data Preparation

Beauty Intelligence:
What Drives Customer Satisfaction in the Global Skincare & Cosmetics Industry?

---

#### Research Questions

- Which brands receive the highest customer ratings?
- Which product categories perform best?
- Does price influence ratings?
- Which regions perform best?
- What ingredients appear in highly rated products?
- What recommendations can be made for beauty companies?
---

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Found this is needed to see all columns
pd.set_option('display.max_columns', None)

In [2]:
# Product dataset
products = pd.read_csv("../data/raw/product_info.csv")

# Review datasets
review1 = pd.read_csv("../data/raw/reviews_0-250.csv")
review2 = pd.read_csv("../data/raw/reviews_250-500.csv")
review3 = pd.read_csv("../data/raw/reviews_500-750.csv")
review4 = pd.read_csv("../data/raw/reviews_750-1250.csv")
review5 = pd.read_csv("../data/raw/reviews_1250-end.csv")

C:\Users\meisn\AppData\Local\Temp\ipykernel_24404\238012333.py:5: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  review1 = pd.read_csv("../data/raw/reviews_0-250.csv")
C:\Users\meisn\AppData\Local\Temp\ipykernel_24404\238012333.py:8: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  review4 = pd.read_csv("../data/raw/reviews_750-1250.csv")
C:\Users\meisn\AppData\Local\Temp\ipykernel_24404\238012333.py:9: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  review5 = pd.read_csv("../data/raw/reviews_1250-end.csv")

In [3]:
products.head()

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,variation_desc,ingredients,price_usd,value_price_usd,sale_price_usd,limited_edition,new,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P473671,Fragrance Discovery Set,6342,19-69,6320,3.6364,11.0,NaN,NaN,NaN,NaN,"['Capri Eau de Parfum:', 'Alcohol Denat. (SD A...",35.0,NaN,NaN,0,0,1,0,0,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342,19-69,3827,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,NaN,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0,NaN,NaN,0,0,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,85.0,30.0
2,P473662,Rainbow Bar Eau de Parfum,6342,19-69,3253,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,NaN,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0,NaN,NaN,0,0,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
3,P473660,Kasbah Eau de Parfum,6342,19-69,3018,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,NaN,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0,NaN,NaN,0,0,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
4,P473658,Purple Haze Eau de Parfum,6342,19-69,2691,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,NaN,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0,NaN,NaN,0,0,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0

In [4]:
review1.head()

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,1741593524,5,1.0,1.0,2,0,2,2023-02-01,I use this with the Nudestix “Citrus Clean Bal...,Taught me how to double cleanse!,NaN,brown,dry,black,P504322,Gentle Hydra-Gel Face Cleanser,NUDESTIX,19.0
1,1,31423088263,1,0.0,NaN,0,0,0,2023-03-21,I bought this lip mask after reading the revie...,Disappointed,NaN,NaN,NaN,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
2,2,5061282401,5,1.0,NaN,0,0,0,2023-03-21,My review title says it all! I get so excited ...,New Favorite Routine,light,brown,dry,blonde,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
3,3,6083038851,5,1.0,NaN,0,0,0,2023-03-20,I’ve always loved this formula for a long time...,Can't go wrong with any of them,NaN,brown,combination,black,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
4,4,47056667835,5,1.0,NaN,0,0,0,2023-03-20,"If you have dry cracked lips, this is a must h...",A must have !!!,light,hazel,combination,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0

In [5]:
review2.head()

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,2190293206,2,0.0,NaN,0,0,0,2023-03-19,Used to swear by this product but hate the sme...,NaN,lightMedium,brown,combination,brown,P443842,Retinol Anti-Aging Serum,The INKEY List,12.99
1,1,9113341005,5,1.0,NaN,0,0,0,2023-03-18,I’ve only been using this for a week and my sk...,More tolerable than The Ordinary,deep,brown,normal,black,P443842,Retinol Anti-Aging Serum,The INKEY List,12.99
2,2,23866342710,1,0.0,1.000000,13,0,13,2023-03-12,"Why, why, why would you change the formula?!!!...",New formula is awful very sad,fairLight,blue,combination,blonde,P443842,Retinol Anti-Aging Serum,The INKEY List,12.99
3,3,1328806527,1,0.0,0.941176,17,1,16,2023-03-12,I have used this product for years and it has ...,Recently reformulated and the new formula is A...,light,brown,combination,gray,P443842,Retinol Anti-Aging Serum,The INKEY List,12.99
4,4,31262847082,5,1.0,1.000000,1,0,1,2023-03-09,Great product for anti-aging Also great for da...,Must have product in my nighttime skincare rou...,lightMedium,hazel,combination,brown,P443842,Retinol Anti-Aging Serum,The INKEY List,12.99

In [6]:
review3.head()

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,2079014373,5,1.0,NaN,0,0,0,2023-03-14,These are the only pimple patches I’ve used th...,Best Pimple Patches,medium,blue,normal,NaN,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0
1,1,12631885517,4,1.0,NaN,0,0,0,2023-02-08,One of my ingrown hair turned inflamed and sor...,It works!,mediumTan,brown,combination,black,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0
2,2,2321761961,5,1.0,1.0,1,0,1,2023-02-05,I have tried 10 different acne/blemish patches...,Good for a large or painful breakout! Sleep in...,NaN,hazel,combination,blonde,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0
3,3,1380382883,4,1.0,NaN,0,0,0,2023-01-24,"Love these for my mid-size breakouts, specifyi...",Micro tips are a plus!!,light,brown,combination,black,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0
4,4,8871759068,4,1.0,1.0,1,0,1,2023-01-15,Best so far - though still not particularly ef...,NaN,NaN,NaN,NaN,NaN,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0

In [7]:
review4.head()

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,8554483509,2,0.0,NaN,0,0,0,2023-03-21,This was gifted by Supergoop! in exchange for ...,Nice packaging but easy to overuse,light,brown,combination,NaN,P467976,(Re)setting 100% Mineral Powder Sunscreen SPF ...,Supergoop!,35.0
1,1,24710523057,2,0.0,1.000000,2,0,2,2023-03-07,I didn’t like it; too much product comes out w...,Packaging is not suits le,NaN,brown,combination,NaN,P467976,(Re)setting 100% Mineral Powder Sunscreen SPF ...,Supergoop!,35.0
2,2,8429283179,5,1.0,0.941176,34,2,32,2023-03-01,Y’all….I’m begging for everyone to read instru...,PLS READ THIS LOL,light,green,normal,brown,P467976,(Re)setting 100% Mineral Powder Sunscreen SPF ...,Supergoop!,35.0
3,3,8105185455,1,0.0,0.000000,5,5,0,2023-02-27,I have not figured out how to use this product...,At a loss,tan,brown,combination,black,P467976,(Re)setting 100% Mineral Powder Sunscreen SPF ...,Supergoop!,35.0
4,4,1515931062,1,0.0,0.000000,7,7,0,2023-02-27,I’m at a loss as to how to use this thing!!! C...,NOT for me!!,fair,blue,combination,blonde,P467976,(Re)setting 100% Mineral Powder Sunscreen SPF ...,Supergoop!,35.0

In [8]:
review5.head()

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,1945004256,5,1.0,0.000000,2,2,0,2022-12-10,I absolutely L-O-V-E this oil. I have acne pro...,A must have!,lightMedium,green,combination,NaN,P379064,Lotus Balancing & Hydrating Natural Face Treat...,Clarins,65.0
1,1,5478482359,3,1.0,0.333333,3,2,1,2021-12-17,I gave this 3 stars because it give me tiny li...,it keeps oily skin under control,mediumTan,brown,oily,black,P379064,Lotus Balancing & Hydrating Natural Face Treat...,Clarins,65.0
2,2,29002209922,5,1.0,1.000000,2,0,2,2021-06-07,Works well as soon as I wash my face and pat d...,Worth the money!,lightMedium,brown,dry,black,P379064,Lotus Balancing & Hydrating Natural Face Treat...,Clarins,65.0
3,3,7391078463,5,1.0,1.000000,2,0,2,2021-05-21,"this oil helped with hydration and breakouts, ...",best face oil,lightMedium,brown,combination,blonde,P379064,Lotus Balancing & Hydrating Natural Face Treat...,Clarins,65.0
4,4,1766313888,5,1.0,1.000000,13,0,13,2021-03-29,This is my first product review ever so that s...,Maskne miracle,mediumTan,brown,combination,black,P379064,Lotus Balancing & Hydrating Natural Face Treat...,Clarins,65.0

In [9]:
# Merge the reviews
all_reviews = pd.concat([review1, review2, review3, review4, review5],ignore_index=True)

In [10]:
all_reviews.shape

(1094411, 19)

#### Products df
---

In [11]:
products.columns

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price'],
      dtype='object')

In [12]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8494 entries, 0 to 8493
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          8494 non-null   object
 1   product_name        8494 non-null   object
 2   brand_id            8494 non-null   int64
 3   brand_name          8494 non-null   object
 4   loves_count         8494 non-null   int64
 5   rating              8216 non-null   float64
 6   reviews             8216 non-null   float64
 7   size                6863 non-null   object
 8   variation_type      7050 non-null   object
 9   variation_value     6896 non-null   object
 10  variation_desc      1250 non-null   object
 11  ingredients         7549 non-null   object
 12  price_usd           8494 non-null   float64
 13  value_price_usd     451 non-null    float64
 14  sale_price_usd      270 non-null    float64
 15  limited_edition     8494 non-null   int64
 16  new                 8494 non-null   int64
 17  online_only         8494 non-null   int64
 18  out_of_stock        8494 non-null   int64
 19  sephora_exclusive   8494 non-null   int64
 20  highlights          6287 non-null   object
 21  primary_category    8494 non-null   object
 22  secondary_category  8486 non-null   object
 23  tertiary_category   7504 non-null   object
 24  child_count         8494 non-null   int64
 25  child_max_price     2754 non-null   float64
 26  child_min_price     2754 non-null   float64
dtypes: float64(7), int64(8), object(12)
memory usage: 1.7+ MB

In [13]:
products.describe()

,brand_id,loves_count,rating,reviews,price_usd,value_price_usd,sale_price_usd,limited_edition,new,online_only,out_of_stock,sephora_exclusive,child_count,child_max_price,child_min_price
count,8494.000000,8.494000e+03,8216.000000,8216.000000,8494.000000,451.000000,270.000000,8494.000000,8494.000000,8494.000000,8494.000000,8494.000000,8494.000000,2754.000000,2754.000000
mean,5422.440546,2.917957e+04,4.194513,448.545521,51.655595,91.168537,20.207889,0.070285,0.071698,0.219096,0.073699,0.279374,1.631622,53.792023,39.665802
std,1709.595957,6.609212e+04,0.516694,1101.982529,53.669234,79.195631,24.327352,0.255642,0.258002,0.413658,0.261296,0.448718,5.379470,58.765894,38.685720
min,1063.000000,0.000000e+00,1.000000,1.000000,3.000000,0.000000,1.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000
25%,5333.000000,3.758000e+03,3.981725,26.000000,25.000000,45.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22.000000,19.000000
50%,6157.500000,9.880000e+03,4.289350,122.000000,35.000000,67.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,32.000000,28.000000
75%,6328.000000,2.684125e+04,4.530525,418.000000,58.000000,108.500000,25.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,59.000000,42.000000
max,8020.000000,1.401068e+06,5.000000,21281.000000,1900.000000,617.000000,320.000000,1.000000,1.000000,1.000000,1.000000,1.000000,105.000000,570.000000,400.000000

In [14]:
products.isnull().sum()

product_id               0
product_name             0
brand_id                 0
brand_name               0
loves_count              0
rating                 278
reviews                278
size                  1631
variation_type        1444
variation_value       1598
variation_desc        7244
ingredients            945
price_usd                0
value_price_usd       8043
sale_price_usd        8224
limited_edition          0
new                      0
online_only              0
out_of_stock             0
sephora_exclusive        0
highlights            2207
primary_category         0
secondary_category       8
tertiary_category      990
child_count              0
child_max_price       5740
child_min_price       5740
dtype: int64

In [15]:
products.duplicated().sum()

np.int64(0)

In [16]:
# Right away I will drop any 'child' columns as these are not needed
products = products.drop(columns=["child_count", "child_max_price", "child_min_price"])

# Dropping these columns because most of their data is null
products = products.drop(columns=["value_price_usd", "sale_price_usd", "variation_desc", "variation_type", "variation_value"])

# Dropping rows with no rating/reviews
products = products.dropna(subset=["rating", "reviews"])

In [17]:
products[["size"]].head(8)

              size
0              NaN
1   3.4 oz/ 100 mL
2   3.4 oz/ 100 mL
3   3.4 oz/ 100 mL
4   3.4 oz/ 100 mL
5  0.25 oz/ 7.5 mL
6  0.25 oz/ 7.5 mL
7   3.4 oz/ 100 mL

In [18]:
products[["ingredients"]].head(8)

                                         ingredients
0  ['Capri Eau de Parfum:', 'Alcohol Denat. (SD A...
1  ['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...
2  ['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...
3  ['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...
4  ['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...
5  ['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...
6  ['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...
7  ['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...

In [19]:
products[["highlights"]].head(8)

                                          highlights
0  ['Unisex/ Genderless Scent', 'Warm &Spicy Scen...
1  ['Unisex/ Genderless Scent', 'Layerable Scent'...
2  ['Unisex/ Genderless Scent', 'Layerable Scent'...
3  ['Unisex/ Genderless Scent', 'Layerable Scent'...
4  ['Unisex/ Genderless Scent', 'Layerable Scent'...
5  ['Warm &Spicy Scent', 'Unisex/ Genderless Scen...
6  ['Unisex/ Genderless Scent', 'Layerable Scent'...
7  ['Unisex/ Genderless Scent', 'allure 2022 Best...

In [20]:
products[["tertiary_category"]].head(8)

           tertiary_category
0          Perfume Gift Sets
1                    Perfume
2                    Perfume
3                    Perfume
4                    Perfume
5  Rollerballs & Travel Size
6  Rollerballs & Travel Size
7                    Perfume

In [21]:
products.tertiary_category.unique()

array(['Perfume Gift Sets', 'Perfume', 'Rollerballs & Travel Size',
       'Body Lotions & Body Oils', nan, 'Cologne', 'Diffusers',
       'Deodorant & Antiperspirant', 'Candles', 'Hair Masks',
       'Leave-In Conditioner', 'Shampoo', 'Hair Oil',
       'Hair Styling Products', 'Scalp Treatments', 'Conditioner',
       'Lip Balm & Treatment', 'Moisturizers', 'Face Serums',
       'Eye Creams & Treatments', 'Face Sunscreen',
       'Face Wash & Cleansers', 'Face Oils', 'Toners', 'Face Masks',
       'Facial Peels', 'Hand Cream & Foot Cream',
       'Decollete & Neck Creams', 'Exfoliators', 'Hair Spray',
       'Hair Primers', 'Tinted Moisturizer', 'Mascara',
       'Setting Spray & Powder', 'Highlighter', 'Concealer', 'Eyebrow',
       'Blush', 'Face Sets', 'Dry Shampoo', 'Curling Irons',
       'Brushes & Combs', 'Hair Straighteners & Flat Irons',
       'Hair Dryers', 'Eyeshadow', 'Lipstick', 'Eye Palettes', 'Contour',
       'Lip Gloss', 'Eye Brushes', 'Foundation', 'False Eyelashes',
       'Cheek Palettes', 'Lip Liner', 'Bronzer', 'Face Brushes',
       'Tweezers & Eyebrow Tools', 'Eye Sets', 'Eye Primer', 'Eyeliner',
       'Sharpeners', 'Accessories', 'Liquid Lipstick', 'Face Primer',
       'Lip Sets', 'Body Wash & Shower Gel', 'BB & CC Cream', 'Eye Masks',
       'Facial Rollers', 'Anti-Aging', 'Face Wipes',
       'Blemish & Acne Treatments', 'Sponges & Applicators',
       'Brush Cleaners', 'Makeup Removers', 'Brush Sets', 'Night Creams',
       'Mists & Essences', 'Scrub & Exfoliants', 'Color Correct',
       'Damaged Hair', 'Hair Thinning & Hair Loss', 'Color Care',
       'Cologne Gift Sets', 'Lip Plumper', 'Beauty Supplements',
       'Body Mist & Hair Mist', 'Cellulite & Stretch Marks',
       'Body Sunscreen', 'Sheet Masks', 'For Body', 'For Face',
       'Face Wash', 'Moisturizer & Treatments', 'Eye Cream',
       'Skincare Sets', 'Aftershave', 'Facial Cleansing Brushes',
       'Shaving', 'Hair Dye & Root Touch-Ups', 'Hair Supplements',
       'Intimate Care', 'Lip Stain', 'Eyelash Curlers',
       'Makeup Bags & Travel Cases', 'Blotting Papers', 'BB & CC Creams',
       'Under-Eye Concealer', 'Makeup & Travel Cases',
       'Holistic Wellness', 'Teeth Whitening', 'Bath Soaks & Bubble Bath',
       'Hair Removal', 'Sunscreen', 'Body Products',
       'Shampoo & Conditioner', 'Hand Sanitizer & Hand Soap',
       'Lip Brushes', 'Manicure & Pedicure Tools'], dtype=object)

In [22]:
products["tertiary_category"] = products["tertiary_category"].fillna("unknown")
products["secondary_category"] = products["secondary_category"].fillna("unknown")
products["size"] = products["size"].fillna("unknown")

# Keeping this as a list for now to make it easier for later use (will take care of this in a later notebook)
products["highlights"] = products["highlights"].fillna("[]")
products["ingredients"] = products["ingredients"].fillna('')

In [23]:
products.isnull().sum()

product_id            0
product_name          0
brand_id              0
brand_name            0
loves_count           0
rating                0
reviews               0
size                  0
ingredients           0
price_usd             0
limited_edition       0
new                   0
online_only           0
out_of_stock          0
sephora_exclusive     0
highlights            0
primary_category      0
secondary_category    0
tertiary_category     0
dtype: int64

In [24]:
products["price_usd"].unique()

array([  35.  ,  195.  ,   30.  ,   38.  ,   29.  ,   80.  ,   12.  ,
         26.  ,   84.  ,   28.  ,   77.  ,  181.  ,  210.  ,  135.  ,
        295.  ,  130.  ,  112.  ,   55.  ,   82.  ,   39.  ,   40.  ,
         24.  ,   25.  ,   32.  ,   36.  ,   15.  ,   56.  ,  145.  ,
        200.  ,  260.  ,  100.  ,   98.  ,  115.  ,   68.  ,   88.  ,
         94.  ,  118.  ,   72.  ,   95.  ,   65.  ,   58.  ,   74.  ,
         85.  ,   70.  ,   96.  ,   44.  ,   22.  ,  105.  ,  106.  ,
         60.  ,   62.  ,   49.  ,   59.  ,   23.  ,   34.  ,   45.  ,
         37.  ,   50.  ,   48.  ,   20.  ,   19.  ,   18.  ,  120.  ,
         10.  ,   16.  ,  150.  ,   21.  ,    9.  ,   17.  ,   13.  ,
          6.  ,   22.5 ,   69.  ,  155.  ,  122.  ,  110.  ,   76.  ,
         33.  ,   64.  ,  174.  ,  160.  ,  126.  ,   79.  ,  158.  ,
         42.  ,   52.  ,   75.  ,   86.  ,  144.  ,  152.  ,  102.  ,
        186.  ,   99.  ,   27.  ,  142.  ,  290.  ,  180.  ,  390.  ,
        220.  ,  215.  ,   92.  ,   83.  ,   57.  ,   93.  ,  305.  ,
        185.  ,  114.  ,  199.  ,  129.  ,  249.  ,   14.  ,   31.  ,
          5.  ,  239.  ,  149.  ,  299.  ,  159.  ,  119.  ,  219.  ,
        245.  ,   54.  ,   66.  ,   46.  ,   53.  ,  107.  ,   19.95,
         29.95,   27.99,   21.99,   23.95,   24.99,   49.95,   29.99,
         23.99,   43.  ,  123.  ,  165.  ,  133.  ,  101.  ,  140.  ,
        117.  ,   78.  ,  104.  ,   81.  ,   90.  ,  147.  ,  125.  ,
        139.  ,  136.  ,  128.  ,  166.  ,  156.  ,    7.  ,   41.  ,
        124.  ,   67.  ,   47.  ,  132.  ,   32.5 ,   23.5 ,   71.  ,
         26.5 ,   34.5 ,   19.5 ,   18.5 ,    6.5 ,   31.5 ,   61.  ,
         11.  ,   24.5 ,  189.  ,   87.  ,   39.5 ,   89.  ,   49.5 ,
         16.5 ,   29.5 ,  170.  ,  175.  ,  116.  ,  134.  ,  143.  ,
        320.  ,  225.  ,  310.  ,  370.  ,  240.  ,  255.  ,  300.  ,
        360.  ,  205.  ,  465.  ,  169.  ,  349.  ,  179.  ,  190.  ,
        285.  ,  108.  ,   63.  ,  275.  ,  329.  ,   10.99,  279.  ,
        399.  ,   51.  ,  113.  ,  111.  ,  154.  ,  131.  ,   91.  ,
        235.  ,  141.  ,  148.  ,  198.  ,  449.  ,   28.5 ,   14.5 ,
        138.  ,  230.  ,  340.  ,  265.  ,   73.  ,   38.5 ,   40.5 ,
         52.5 ,   42.5 ,   12.5 ,   10.5 ,  250.  ,  380.  ,  425.  ,
        270.  ,  410.  ,    4.  ,  163.  ,    8.  ,   13.5 ,   97.  ,
         37.5 ,    8.99,  429.  ,  395.  ,  169.99,   41.5 ,    3.  ,
          4.5 ,    5.5 ,    3.5 ,    4.95, 1900.  ,  400.  ,  315.  ,
        139.99,  189.99,  149.99,  199.99,  179.99,  146.  ,   11.99,
          5.99,    9.99,   12.99,   15.99,   14.99,    7.99,   13.99,
          7.49,   17.99,   19.99,   21.7 ,   15.7 ,    9.5 ,    8.9 ,
          6.7 ,   10.9 ,   30.8 ,    7.8 ,   11.1 ,   24.3 ,   14.2 ,
         11.7 ,   13.3 ,   12.2 ,    7.5 ,    8.3 ,    7.2 ,   30.9 ,
          9.4 ,    6.4 ,   19.8 ,   14.3 ,    8.5 ,   40.7 ,  188.  ])

In [25]:
products["price_usd"].describe()

count    8216.000000
mean       51.228229
std        53.406409
min         3.000000
25%        25.000000
50%        35.000000
75%        58.000000
max      1900.000000
Name: price_usd, dtype: float64

In [26]:
products["product_id"].duplicated().sum()

np.int64(0)

In [27]:
# Incase there is any space I do not see
products["product_name"].str.strip()

0                Fragrance Discovery Set
1                La Habana Eau de Parfum
2              Rainbow Bar Eau de Parfum
3                   Kasbah Eau de Parfum
4              Purple Haze Eau de Parfum
                      ...
8487                Black Opium Gift Set
8488        Libre Eau de Parfum Gift Set
8489    Couture Clutch Eyeshadow Palette
8490               L'Homme Eau de Parfum
8491    Mon Paris Eau de Parfum Gift Set
Name: product_name, Length: 8216, dtype: object

In [28]:
products["sephora_exclusive"].unique()

array([0, 1])

In [29]:
products["primary_category"].unique()

array(['Fragrance', 'Bath & Body', 'Mini Size', 'Hair', 'Makeup',
       'Skincare', 'Tools & Brushes', 'Men', 'Gifts'], dtype=object)

In [30]:
products["secondary_category"].unique()

array(['Value & Gift Sets', 'Women', 'Body Moisturizers', 'Fragrance',
       'Men', 'Candles & Home Scents', 'Body Care',
       'Hair Styling & Treatments', 'Shampoo & Conditioner', 'Mini Size',
       'Lip', 'Moisturizers', 'Treatments', 'Eye Care',
       'Lip Balms & Treatments', 'Sunscreen', 'Cleansers', 'Masks',
       'Skincare', 'Face', 'Eye', 'Cheek', 'Hair', 'Tools',
       'Brushes & Applicators', 'Makeup Palettes', 'Beauty Tools',
       'Accessories', 'Makeup', 'Bath & Shower', 'Wellness',
       'High Tech Tools', 'Shop by Concern', 'Self Tanners', 'Shaving',
       'Hair Tools', 'Nail', 'unknown', 'Beauty Accessories',
       'Beauty Supplements', 'Other Needs', 'Bath & Body'], dtype=object)

In [31]:
# Getting a more detailed look at each category, I should only need skincare ...
second_cat = products[["primary_category","secondary_category", "tertiary_category", "product_name"]]

In [32]:
second_cat.head(20)

,primary_category,secondary_category,tertiary_category,product_name
0,Fragrance,Value & Gift Sets,Perfume Gift Sets,Fragrance Discovery Set
1,Fragrance,Women,Perfume,La Habana Eau de Parfum
2,Fragrance,Women,Perfume,Rainbow Bar Eau de Parfum
3,Fragrance,Women,Perfume,Kasbah Eau de Parfum
4,Fragrance,Women,Perfume,Purple Haze Eau de Parfum
5,Fragrance,Women,Rollerballs & Travel Size,Kasbah Eau de Parfum Travel Spray
6,Fragrance,Women,Rollerballs & Travel Size,Purple Haze Eau de Parfum Travel Spray
7,Fragrance,Women,Perfume,Invisible Post Eau de Parfum
8,Fragrance,Women,Perfume,Capri Eau de Parfum
9,Fragrance,Women,Rollerballs & Travel Size,Invisible Post Eau de Parfum Travel Spray
10,Fragrance,Women,Rollerballs & Travel Size,Rainbow Bar Eau de Parfum Travel Spray
11,Fragrance,Women,Rollerballs & Travel Size,Capri Eau de Parfum Travel Spray
12,Fragrance,Women,Perfume,L'air Barbes Eau de Parfum
13,Fragrance,Women,Rollerballs & Travel Size,L'air Barbes Eau de Parfum Travel Spray
14,Bath & Body,Body Moisturizers,Body Lotions & Body Oils,AFRICAN Beauty Butter- Intensive Dry Skin Trea...
15,Bath & Body,Value & Gift Sets,unknown,African Beauty Butter Mini Gift Set
16,Bath & Body,Value & Gift Sets,unknown,African Beauty Butter Collection Deluxe Tin
17,Bath & Body,Body Moisturizers,Body Lotions & Body Oils,Mini AFRICAN Beauty Butter- Intensive Dry Skin...
18,Fragrance,Value & Gift Sets,Perfume Gift Sets,ABBOTT Sampler Set
19,Fragrance,Women,Perfume,The Cape Perfume

In [33]:
second_cat.primary_category.unique()

array(['Fragrance', 'Bath & Body', 'Mini Size', 'Hair', 'Makeup',
       'Skincare', 'Tools & Brushes', 'Men', 'Gifts'], dtype=object)

In [34]:
second_cat.shape

(8216, 4)

In [35]:
# Filter new DF to only inclide the 'skincare' then drop this column as it is all skincare
skincare_products = products[products["primary_category"] == "Skincare"].drop(columns=["primary_category"])

In [36]:
skincare_products.head()

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,ingredients,price_usd,limited_edition,new,online_only,out_of_stock,sephora_exclusive,highlights,secondary_category,tertiary_category
89,P439055,GENIUS Sleeping Collagen Moisturizer,6018,Algenist,33910,4.5413,1321.0,2 oz/ 60 mL,"['Collagen (Vegan)*, Water (Aqua, Eau), Ethylh...",98.0,0,0,0,0,1,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Moisturizers,Moisturizers
90,P421277,GENIUS Liquid Collagen Serum,6018,Algenist,67870,4.0259,1159.0,1 oz / 30 mL,"['Collagen (Vegan)*, Water (Aqua, Eau), Propan...",115.0,0,0,0,0,1,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Treatments,Face Serums
91,P467602,Triple Algae Eye Renewal Balm Eye Cream,6018,Algenist,17890,4.5306,1142.0,unknown,"['Aqua (Water/Eau), Stearic Acid, Isopropyl Is...",68.0,0,0,0,0,1,[],Eye Care,Eye Creams & Treatments
92,P432045,GENIUS Liquid Collagen Lip Treatment,6018,Algenist,44448,3.8721,649.0,.5 oz / 15 mL,"['Collagen (Vegan)*, Water (Aqua, Eau), Glycer...",29.0,0,0,0,0,1,"['Vegan', 'Good for: Loss of firmness', 'Plump...",Lip Balms & Treatments,unknown
93,P311143,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,6018,Algenist,27278,4.4134,508.0,1 oz,"['Octinoxate 7.5%, Titanium Dioxide 2%, Zinc O...",28.0,0,0,0,0,0,"['Vegan', 'Hypoallergenic', 'UV Protection', '...",Sunscreen,Face Sunscreen

In [37]:
skincare_products.shape

(2351, 18)

In [38]:
skincare_products["secondary_category"].unique()

array(['Moisturizers', 'Treatments', 'Eye Care', 'Lip Balms & Treatments',
       'Sunscreen', 'Cleansers', 'Value & Gift Sets', 'Masks',
       'Mini Size', 'Wellness', 'High Tech Tools', 'Self Tanners',
       'Shop by Concern'], dtype=object)

In [39]:
skincare_products["tertiary_category"].unique()

array(['Moisturizers', 'Face Serums', 'Eye Creams & Treatments',
       'unknown', 'Face Sunscreen', 'Face Wash & Cleansers', 'Face Oils',
       'Toners', 'Face Masks', 'Facial Peels', 'Decollete & Neck Creams',
       'Exfoliators', 'Eye Masks', 'Facial Rollers', 'Anti-Aging',
       'Face Wipes', 'Blemish & Acne Treatments', 'Night Creams',
       'Mists & Essences', 'Beauty Supplements', 'Body Sunscreen',
       'Sheet Masks', 'For Body', 'Makeup Removers', 'For Face',
       'Facial Cleansing Brushes', 'Blotting Papers', 'BB & CC Creams',
       'Holistic Wellness', 'Teeth Whitening', 'Hair Removal'],
      dtype=object)

In [40]:
skincare_products.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2351 entries, 89 to 8428
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          2351 non-null   object
 1   product_name        2351 non-null   object
 2   brand_id            2351 non-null   int64
 3   brand_name          2351 non-null   object
 4   loves_count         2351 non-null   int64
 5   rating              2351 non-null   float64
 6   reviews             2351 non-null   float64
 7   size                2351 non-null   object
 8   ingredients         2351 non-null   object
 9   price_usd           2351 non-null   float64
 10  limited_edition     2351 non-null   int64
 11  new                 2351 non-null   int64
 12  online_only         2351 non-null   int64
 13  out_of_stock        2351 non-null   int64
 14  sephora_exclusive   2351 non-null   int64
 15  highlights          2351 non-null   object
 16  secondary_category  2351 non-null   object
 17  tertiary_category   2351 non-null   object
dtypes: float64(3), int64(7), object(8)
memory usage: 349.0+ KB

In [41]:
skincare_products['reviews'] = skincare_products['reviews'].astype(int)

In [42]:
skincare_products.head()

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,ingredients,price_usd,limited_edition,new,online_only,out_of_stock,sephora_exclusive,highlights,secondary_category,tertiary_category
89,P439055,GENIUS Sleeping Collagen Moisturizer,6018,Algenist,33910,4.5413,1321,2 oz/ 60 mL,"['Collagen (Vegan)*, Water (Aqua, Eau), Ethylh...",98.0,0,0,0,0,1,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Moisturizers,Moisturizers
90,P421277,GENIUS Liquid Collagen Serum,6018,Algenist,67870,4.0259,1159,1 oz / 30 mL,"['Collagen (Vegan)*, Water (Aqua, Eau), Propan...",115.0,0,0,0,0,1,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Treatments,Face Serums
91,P467602,Triple Algae Eye Renewal Balm Eye Cream,6018,Algenist,17890,4.5306,1142,unknown,"['Aqua (Water/Eau), Stearic Acid, Isopropyl Is...",68.0,0,0,0,0,1,[],Eye Care,Eye Creams & Treatments
92,P432045,GENIUS Liquid Collagen Lip Treatment,6018,Algenist,44448,3.8721,649,.5 oz / 15 mL,"['Collagen (Vegan)*, Water (Aqua, Eau), Glycer...",29.0,0,0,0,0,1,"['Vegan', 'Good for: Loss of firmness', 'Plump...",Lip Balms & Treatments,unknown
93,P311143,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,6018,Algenist,27278,4.4134,508,1 oz,"['Octinoxate 7.5%, Titanium Dioxide 2%, Zinc O...",28.0,0,0,0,0,0,"['Vegan', 'Hypoallergenic', 'UV Protection', '...",Sunscreen,Face Sunscreen

In [43]:
skincare_products.highlights.unique()

array(["['Vegan', 'Good for: Loss of firmness', 'Collagen', 'Hypoallergenic', 'Without Parabens', 'Best for Dry, Combo, Normal Skin']",
       '[]',
       "['Vegan', 'Good for: Loss of firmness', 'Plumping', 'Collagen', 'Hypoallergenic', 'Best for Dry, Combo, Normal Skin']",
       ...,
       "['Vegan', 'Hyaluronic Acid', 'Clean at Sephora', 'Hydrating', 'Good for: Dryness', 'Best for Dry, Combo, Normal Skin']",
       "['Vegan', 'Good for: Pores', 'Clean + Planet Positive', 'Good for: Acne/Blemishes', 'Best for Oily, Combo, Normal Skin', 'Without Sulfates SLS & SLES']",
       "['Vegan', 'Good for: Dullness/Uneven Texture', 'Vitamin C', 'Plumping', 'Clean at Sephora', 'Hydrating']"],
      shape=(1623,), dtype=object)

In [44]:
# Porducts are done being cleaned, saving as csv
skincare_products.to_csv("../data/processed/products_clean.csv")

#### Reviews df

In [45]:
all_reviews.head(2)

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,1741593524,5,1.0,1.0,2,0,2,2023-02-01,I use this with the Nudestix “Citrus Clean Bal...,Taught me how to double cleanse!,NaN,brown,dry,black,P504322,Gentle Hydra-Gel Face Cleanser,NUDESTIX,19.0
1,1,31423088263,1,0.0,NaN,0,0,0,2023-03-21,I bought this lip mask after reading the revie...,Disappointed,NaN,NaN,NaN,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0

In [46]:
all_reviews.shape

(1094411, 19)

In [47]:
# Before anything i need to make sure only the matching product ideas on the review and products dfs are matching
all_reviews = all_reviews.merge(skincare_products[["product_id"]],on="product_id",how="inner")

In [48]:
all_reviews.head(5)

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,1741593524,5,1.0,1.0,2,0,2,2023-02-01,I use this with the Nudestix “Citrus Clean Bal...,Taught me how to double cleanse!,NaN,brown,dry,black,P504322,Gentle Hydra-Gel Face Cleanser,NUDESTIX,19.0
1,1,31423088263,1,0.0,NaN,0,0,0,2023-03-21,I bought this lip mask after reading the revie...,Disappointed,NaN,NaN,NaN,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
2,2,5061282401,5,1.0,NaN,0,0,0,2023-03-21,My review title says it all! I get so excited ...,New Favorite Routine,light,brown,dry,blonde,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
3,3,6083038851,5,1.0,NaN,0,0,0,2023-03-20,I’ve always loved this formula for a long time...,Can't go wrong with any of them,NaN,brown,combination,black,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
4,4,47056667835,5,1.0,NaN,0,0,0,2023-03-20,"If you have dry cracked lips, this is a must h...",A must have !!!,light,hazel,combination,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0

In [49]:
all_reviews.shape

(1094411, 19)

In [50]:
all_reviews.isnull().sum()

Unnamed: 0                       0
author_id                        0
rating                           0
is_recommended              167988
helpfulness                 561592
total_feedback_count             0
total_neg_feedback_count         0
total_pos_feedback_count         0
submission_time                  0
review_text                   1444
review_title                310654
skin_tone                   170539
eye_color                   209628
skin_type                   111557
hair_color                  226768
product_id                       0
product_name                     0
brand_name                       0
price_usd                        0
dtype: int64

In [51]:
all_reviews['helpfulness'].value_counts(dropna=False).head(10)

helpfulness
NaN         561592
1.000000    251334
0.000000     47741
0.500000     34987
0.666667     24887
0.750000     18160
0.800000     13604
0.833333     10324
0.333333      8465
0.857143      8213
Name: count, dtype: int64

In [52]:
# Drop unnecessary index column
all_reviews = all_reviews.drop(columns="Unnamed: 0")
all_reviews = all_reviews.drop(columns="skin_tone")
all_reviews = all_reviews.drop(columns="hair_color")
all_reviews = all_reviews.drop(columns="eye_color")



# Remove reviews without review text
all_reviews = all_reviews.dropna(subset=["review_text"])

# Fill values that make sense
all_reviews["helpfulness"] = all_reviews["helpfulness"].fillna(0)
all_reviews["review_title"] = all_reviews["review_title"].fillna("No Title")

# Fill with uknown
all_reviews["skin_type"] = all_reviews["skin_type"].fillna("unknown")

# Date column
all_reviews['submission_time'] = pd.to_datetime(all_reviews['submission_time'], errors='coerce')

In [53]:
all_reviews.groupby('skin_type')['rating'].mean()

skin_type
combination    4.309442
dry            4.291003
normal         4.282086
oily           4.270977
unknown        4.313097
Name: rating, dtype: float64

In [54]:
all_reviews.is_recommended.unique()

array([ 1.,  0., nan])

In [55]:
all_reviews.isnull().sum()

author_id                        0
rating                           0
is_recommended              167988
helpfulness                      0
total_feedback_count             0
total_neg_feedback_count         0
total_pos_feedback_count         0
submission_time                  0
review_text                      0
review_title                     0
skin_type                        0
product_id                       0
product_name                     0
brand_name                       0
price_usd                        0
dtype: int64

In [56]:
all_reviews["is_recommended"].value_counts(dropna=False)

is_recommended
1.0    776965
NaN    167988
0.0    148014
Name: count, dtype: int64

In [57]:
all_reviews["is_recommended"] = all_reviews["is_recommended"].fillna("unknown")

In [58]:
all_reviews.duplicated().sum()

np.int64(241)

In [59]:
duplicates = all_reviews[all_reviews.duplicated(keep=False)]
duplicates.sort_values("product_id").head(1)

,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_type,product_id,product_name,brand_name,price_usd
729762,6007590540,5,unknown,0.0,1,1,0,2014-05-05,Makes your face soft and it does not dry your ...,Gr8 product!!,unknown,P122661,7 Day Face Scrub Cream Rinse-Off Formula,CLINIQUE,26.0

In [60]:
all_reviews = all_reviews.drop_duplicates()

In [61]:
all_reviews.duplicated().sum()

np.int64(0)

In [62]:
all_reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1092726 entries, 0 to 1094410
Data columns (total 15 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   author_id                 1092726 non-null  object
 1   rating                    1092726 non-null  int64
 2   is_recommended            1092726 non-null  object
 3   helpfulness               1092726 non-null  float64
 4   total_feedback_count      1092726 non-null  int64
 5   total_neg_feedback_count  1092726 non-null  int64
 6   total_pos_feedback_count  1092726 non-null  int64
 7   submission_time           1092726 non-null  datetime64[ns]
 8   review_text               1092726 non-null  object
 9   review_title              1092726 non-null  object
 10  skin_type                 1092726 non-null  object
 11  product_id                1092726 non-null  object
 12  product_name              1092726 non-null  object
 13  brand_name                1092726 non-null  object
 14  price_usd                 1092726 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(4), object(8)
memory usage: 133.4+ MB

In [63]:
all_reviews["helpfulness"] = all_reviews["helpfulness"].astype(int)

# Need to drop for merge
all_reviews = all_reviews.drop(columns=["product_name", "brand_name", "price_usd", "rating"])

In [64]:
# Review df is done being cleaned for now, saving as csv
all_reviews.to_csv("../data/processed/reviews_clean.csv")

#### Marge

In [65]:
# Merge final clean data
beauty_df = all_reviews.merge(skincare_products, on="product_id", how="inner")

In [66]:
beauty_df.shape

(1092726, 28)

In [67]:
beauty_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1092726 entries, 0 to 1092725
Data columns (total 28 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   author_id                 1092726 non-null  object
 1   is_recommended            1092726 non-null  object
 2   helpfulness               1092726 non-null  int64
 3   total_feedback_count      1092726 non-null  int64
 4   total_neg_feedback_count  1092726 non-null  int64
 5   total_pos_feedback_count  1092726 non-null  int64
 6   submission_time           1092726 non-null  datetime64[ns]
 7   review_text               1092726 non-null  object
 8   review_title              1092726 non-null  object
 9   skin_type                 1092726 non-null  object
 10  product_id                1092726 non-null  object
 11  product_name              1092726 non-null  object
 12  brand_id                  1092726 non-null  int64
 13  brand_name                1092726 non-null  object
 14  loves_count               1092726 non-null  int64
 15  rating                    1092726 non-null  float64
 16  reviews                   1092726 non-null  int64
 17  size                      1092726 non-null  object
 18  ingredients               1092726 non-null  object
 19  price_usd                 1092726 non-null  float64
 20  limited_edition           1092726 non-null  int64
 21  new                       1092726 non-null  int64
 22  online_only               1092726 non-null  int64
 23  out_of_stock              1092726 non-null  int64
 24  sephora_exclusive         1092726 non-null  int64
 25  highlights                1092726 non-null  object
 26  secondary_category        1092726 non-null  object
 27  tertiary_category         1092726 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(12), object(13)
memory usage: 233.4+ MB

In [68]:
beauty_df.isnull().sum()

author_id                   0
is_recommended              0
helpfulness                 0
total_feedback_count        0
total_neg_feedback_count    0
total_pos_feedback_count    0
submission_time             0
review_text                 0
review_title                0
skin_type                   0
product_id                  0
product_name                0
brand_id                    0
brand_name                  0
loves_count                 0
rating                      0
reviews                     0
size                        0
ingredients                 0
price_usd                   0
limited_edition             0
new                         0
online_only                 0
out_of_stock                0
sephora_exclusive           0
highlights                  0
secondary_category          0
tertiary_category           0
dtype: int64

In [69]:
beauty_df.duplicated().sum()

np.int64(2)

In [70]:
beauty_df = beauty_df.sort_index(axis=1)

In [71]:
beauty_df.head(15)

,author_id,brand_id,brand_name,helpfulness,highlights,ingredients,is_recommended,limited_edition,loves_count,new,online_only,out_of_stock,price_usd,product_id,product_name,rating,review_text,review_title,reviews,secondary_category,sephora_exclusive,size,skin_type,submission_time,tertiary_category,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count
0,1741593524,7055,NUDESTIX,1,['Clean at Sephora'],"['Water (Aqua), Dipropylene Glycol, Peg-6 Capr...",1.0,0,177,0,1,0,19.0,P504322,Gentle Hydra-Gel Face Cleanser,5.0000,I use this with the Nudestix “Citrus Clean Bal...,Taught me how to double cleanse!,1,Cleansers,0,2.4 oz / 70 ml,dry,2023-02-01,unknown,2,0,2
1,31423088263,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",0.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,I bought this lip mask after reading the revie...,Disappointed,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,unknown,2023-03-21,unknown,0,0,0
2,5061282401,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,My review title says it all! I get so excited ...,New Favorite Routine,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,dry,2023-03-21,unknown,0,0,0
3,6083038851,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,I’ve always loved this formula for a long time...,Can't go wrong with any of them,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,combination,2023-03-20,unknown,0,0,0
4,47056667835,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,"If you have dry cracked lips, this is a must h...",A must have !!!,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,combination,2023-03-20,unknown,0,0,0
5,42802569154,6125,LANEIGE,1,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,The scent isn’t my favourite but it works grea...,Great!,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,normal,2023-03-19,unknown,1,0,1
6,6941883808,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",0.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,I’ll give this 2 stars for nice packaging and ...,Dried my lips out and clogged my pores,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,combination,2023-03-19,unknown,8,6,2
7,27926227988,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,I use this at night or while I’m putting makeu...,Works great,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,combination,2023-03-19,unknown,0,0,0
8,7656791726,6125,LANEIGE,1,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,I love this stuff. I first had the sample size...,Must have.,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,normal,2023-03-18,unknown,1,0,1
9,38727834382,6125,LANEIGE,1,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,I purchased the Sweet Candy scent at my local ...,RUN TO PURCHASE,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,normal,2023-03-18,unknown,2,0,2
10,45409499927,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,this product is a bit pricey but after using o...,so nourishing,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,dry,2023-03-18,unknown,0,0,0
11,37554855017,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,I use this every night and morning and it work...,Worth the hype,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,dry,2023-03-18,unknown,0,0,0
12,21858073785,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,A little goes a long way. Love the fragrance a...,No Title,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,combination,2023-03-17,unknown,0,0,0
13,22249699172,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",0.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,Honestly I was so excited when I got this in t...,I WISHED I LOVED THIS (not clean ingredients),16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,dry,2023-03-17,unknown,9,5,4
14,1216391002,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",0.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,Does the gummy bear mask smell absolutely deli...,Just meh,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,combination,2023-03-16,unknown,0,0,0

In [72]:
# beauty_df = beauty_df.rename(columns={'rating_x': 'rating', 'product_name_x': 'product_name', 'brand_name_x': 'brand_name', 'price_usd_x': 'price_usd', 'product_name_y': 'product_name', 'brand_name_y': 'brand_name', 'rating_y': 'rating', 'price_usd_y': 'price_usd'})

In [73]:
beauty_df.columns

Index(['author_id', 'brand_id', 'brand_name', 'helpfulness', 'highlights',
       'ingredients', 'is_recommended', 'limited_edition', 'loves_count',
       'new', 'online_only', 'out_of_stock', 'price_usd', 'product_id',
       'product_name', 'rating', 'review_text', 'review_title', 'reviews',
       'secondary_category', 'sephora_exclusive', 'size', 'skin_type',
       'submission_time', 'tertiary_category', 'total_feedback_count',
       'total_neg_feedback_count', 'total_pos_feedback_count'],
      dtype='object')

In [79]:
beauty_df.price_usd.unique()

array([  19.  ,   24.  ,   39.  ,   49.  ,   38.  ,   92.  ,   36.  ,
         60.  ,   68.  ,   14.  ,    6.  ,  122.  ,   52.  ,    7.  ,
         21.  ,   18.  ,   65.  ,   17.  ,   26.  ,   28.  ,   70.  ,
         22.  ,   32.5 ,    3.  ,   15.7 ,   10.  ,   66.  ,   90.  ,
        100.  ,   34.  ,   15.  ,   27.  ,   48.  ,    9.5 ,   38.5 ,
         98.  ,   11.99,    5.99,   51.  ,   35.  ,  245.  ,   99.  ,
         50.  ,   82.  ,   13.  ,   32.  ,   64.  ,   80.  ,   78.  ,
         20.  ,  110.  ,   54.  ,   40.  ,  105.  ,    8.  ,  115.  ,
        195.  ,   23.5 ,  125.  ,   42.  ,    8.9 ,   58.  ,    6.5 ,
         57.  ,   62.  ,    9.99,   45.  ,   33.  ,   46.  ,   72.  ,
         85.  ,   56.  ,   12.  ,   16.  ,   71.  ,   37.  ,   10.9 ,
         89.  ,   30.8 ,  132.  ,   10.99,   30.  ,   41.  ,   74.  ,
        130.  ,   44.  ,   95.  ,  380.  ,   29.  ,  145.  ,   55.  ,
         25.  ,   12.99,   69.  ,    7.8 ,   76.  ,   49.5 ,   88.  ,
         14.99,   11.1 ,   75.  ,   96.  ,    9.  ,  320.  ,  170.  ,
        150.  ,  225.  ,   23.  ,   15.99,  159.  ,   11.7 ,   79.  ,
         83.  ,   43.  ,   13.3 ,   59.  ,  140.  ,   26.5 ,  425.  ,
         34.5 ,  112.  ,   12.2 ,  290.  ,   19.5 ,  255.  ,   47.  ,
          7.5 ,  180.  ,  240.  ,   39.5 ,    8.3 ,   73.  ,    5.5 ,
         63.  ,    3.5 ,   84.  ,  260.  ,    7.2 ,  135.  ,    5.  ,
         86.  ,   97.  ,    7.99,   67.  ,   31.5 ,  215.  ,  120.  ,
         30.9 ,    9.4 ,   87.  ,  129.  ,  146.  ,   94.  ,   10.5 ,
        329.  ,  118.  ,    7.49,   61.  ,  139.  ,  169.99,   93.  ,
          6.4 ,  270.  ,  199.  ,   77.  ,   19.8 ,   31.  ,   14.3 ,
        410.  ,  155.  ,  210.  ,   53.  ,  200.  ,  179.  ,  399.  ,
        219.  ,  449.  ,  429.  ,  390.  ,   17.99,   24.99,  149.  ,
        165.  ,   13.99,  220.  ,    8.5 ,  119.  ,   19.99,  299.  ,
        400.  ,  160.  ,  152.  ,  310.  ,  175.  ,  300.  ,  370.  ,
        275.  ,  102.  ,  190.  ,  230.  ,   21.99,   40.7 ,  279.  ,
          4.  ,  106.  ,  249.  ,  315.  ,  185.  ,  360.  ,  340.  ,
        205.  ,   12.5 ,   11.  ,  465.  , 1900.  ,   24.5 ,  305.  ,
        395.  ,   16.5 ,  235.  ,  198.  ])

In [77]:
beauty_df.brand_name.unique()

array(['NUDESTIX', 'LANEIGE', 'fresh', 'Josie Maran', 'First Aid Beauty',
       'Dr. Dennis Gross Skincare', 'belif', 'Farmacy', 'Drunk Elephant',
       'Youth To The People', 'The Ordinary', 'Sunday Riley', 'Dr. Jart+',
       'Rosebud Perfume Co.', 'Dermalogica', 'Peace Out', 'Origins',
       'Summer Fridays', 'CLINIQUE', 'KORRES', 'Tatcha',
       'SEPHORA COLLECTION', 'bareMinerals', 'Jack Black', 'Bobbi Brown',
       'Charlotte Tilbury', 'Caudalie', 'Glow Recipe', 'Supergoop!',
       'Kate Somerville', 'The INKEY List', 'OLEHENRIKSEN', 'SK-II',
       'Shiseido', 'Isle of Paradise', 'Estée Lauder', 'Clarins', 'Murad',
       "Kiehl's Since 1851", 'IT Cosmetics', 'Skinfix', 'tarte',
       'Wishful', 'goop', 'Biossance', 'Herbivore', 'Peter Thomas Roth',
       'MILK MAKEUP', 'Lancôme', 'Evian', 'Dior', 'innisfree', 'La Mer',
       'Sol de Janeiro', 'Algenist', 'REN Clean Skincare', 'GUERLAIN',
       'Dr. Brandt Skincare', "Paula's Choice", 'KORA Organics',
       'St. Tropez', 'Shani Darden Skin Care', 'Sulwhasoo', 'Alpha-H',
       'Topicals', 'Dr. Barbara Sturm', 'Tata Harper', 'COOLA',
       'Fenty Skin', 'GLO Science', 'Benefit Cosmetics',
       'Augustinus Bader', 'HUM Nutrition', 'Tower 28 Beauty', 'ILIA',
       'JLo Beauty', 'WASO', 'Dr. Zenovia Skincare',
       'Dr. Lara Devgan Scientific Beauty', 'Moon Juice', 'Wander Beauty',
       'MERIT', 'TAN-LUXE', 'alpyn beauty', 'Nécessaire', 'Gucci',
       'CAY SKIN', 'Slip', 'Prima', 'TULA Skincare', 'Mario Badescu',
       'iNNBEAUTY PROJECT', 'Saint Jane Beauty', 'DAMDAM', 'Mount Lai',
       'Koh Gen Do', 'DERMAFLASH', 'ROSE INC',
       'ONE/SIZE by Patrick Starrr', 'LAWLESS', 'Community Sixty-Six',
       'FOREO', 'Naturally Serious', 'MARA', 'Freck Beauty', 'RANAVAT',
       'EADEM', 'PROVEN Skincare', 'HABIT', 'BeautyBio', 'Kosas',
       'Skin Laundry', 'The Nue Co.', 'The Outset', 'Saie', 'Hanni',
       'Flora + Bast', 'NuFACE', 'PMD', "L'Occitane", 'StriVectin',
       'SOBEL SKIN Rx', 'Hyper Skin', 'Kate McLeod', 'FaceGym',
       'ROSE Ingleton MD', 'Hourglass', 'INC.redible', 'iluminage',
       'Glossier', 'lilah b.', 'CANOPY', 'Jillian Dempsey',
       'Danessa Myricks Beauty', 'MACRENE actives', 'TWEEZERMAN',
       'Iconic London', 'Anastasia Beverly Hills', 'caliray', 'Gisou',
       'Soleil Toujours', 'Erno Laszlo'], dtype=object)

In [ ]:
beauty_df.head()

,author_id,brand_id,brand_name,helpfulness,highlights,ingredients,is_recommended,limited_edition,loves_count,new,online_only,out_of_stock,price_usd,product_id,product_name,rating,review_text,review_title,reviews,secondary_category,sephora_exclusive,size,skin_type,submission_time,tertiary_category,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count
0,1741593524,7055,NUDESTIX,1,['Clean at Sephora'],"['Water (Aqua), Dipropylene Glycol, Peg-6 Capr...",1.0,0,177,0,1,0,19.0,P504322,Gentle Hydra-Gel Face Cleanser,5.0000,I use this with the Nudestix “Citrus Clean Bal...,Taught me how to double cleanse!,1,Cleansers,0,2.4 oz / 70 ml,dry,2023-02-01,unknown,2,0,2
1,31423088263,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",0.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,I bought this lip mask after reading the revie...,Disappointed,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,unknown,2023-03-21,unknown,0,0,0
2,5061282401,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,My review title says it all! I get so excited ...,New Favorite Routine,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,dry,2023-03-21,unknown,0,0,0
3,6083038851,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,I’ve always loved this formula for a long time...,Can't go wrong with any of them,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,combination,2023-03-20,unknown,0,0,0
4,47056667835,6125,LANEIGE,0,"['allure 2019 Best of Beauty Award Winner', 'C...","['Diisostearyl Malate, Hydrogenated Polyisobut...",1.0,0,1081315,0,0,0,24.0,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,4.3508,"If you have dry cracked lips, this is a must h...",A must have !!!,16118,Lip Balms & Treatments,1,0.7 oz/ 20 g,combination,2023-03-20,unknown,0,0,0

In [75]:
# Saving final DF
beauty_df.to_csv("../data/processed/final_df.csv")

### Data is cleaned and ready to move on. 
- Text columns such as review_text,	review_title, highlights, and ingredients will be cleaned in a different notebook